### ISSUE TITLE
error: circomlibjs@hsg88/circomlibjs#ffjavascrip.0.1.0 failed to resolve

### ISSUE THREAD

**Issue by kamalbuilds** [Railgun-Community/wallet#77]
GET https://api.github.com/repos/hsg88/circomlibjs/tarball/ffjavascrip.0.1.0 - 404
error: circomlibjs@hsg88/circomlibjs#ffjavascrip.0.1.0 failed to resolve

![image](https://github.com/Railgun-Community/wallet/assets/95926324/de459660-6fa1-454a-85fa-a4c67212323a)

**Comment by kamalbuilds** [comment]
@zy0n @Zorlin @mesquka can you please check into this and tell me a way to resolve this issue , tried a bunch of stuff but still stuck at this from many days ?

**Comment by zy0n** [comment]
> @zy0n @Zorlin @mesquka can you please check into this and tell me a way to resolve this issue , tried a bunch of stuff but still stuck at this from many days ?

Am not sure as to which version bun is trying to install; but if you check [@railgun-community/circomlibjs pkg on npmjs](https://www.npmjs.com/package/@railgun-community/circomlibjs) 
you'll see that its 0.0.8 not 1.1.6 that bun has there? 

this issue is fixed in that package. 
try putting 0.0.8 as the resolution version in the package.json as well;

**Comment by kamalbuilds** [comment]
> > @zy0n @Zorlin @mesquka can you please check into this and tell me a way to resolve this issue , tried a bunch of stuff but still stuck at this from many days ?
> 
> Am not sure as to which version bun is trying to install; but if you check [@railgun-community/circomlibjs pkg on npmjs](https://www.npmjs.com/package/@railgun-community/circomlibjs) you'll see that its 0.0.8 not 1.1.6 that bun has there?
> 
> this issue is fixed in that package. try putting 0.0.8 as the resolution version in the package.json as well;

@zy0n I tried to run a bunch of repos to find which is the ideal setup but the error incurs in all of them .

Providing some of them below for reference and it doesnt seem a bun issue as I tried with npm and yarn too.

1. https://github.com/venture23-zkp/railgun-integrations-ui/blob/develop/package.json
2. https://github.com/zkpay-team/dapp

**Comment by kamalbuilds** [comment]
@zy0n simply trying an `npm i` leads to this common error in all such repos utilsing the railgun packages.

![image](https://github.com/Railgun-Community/wallet/assets/95926324/acdb3193-bb3d-46d4-84c5-fb676010ef3c)

and in the whole project I can find only `hsg88` references in inside package-lock.json 

![image](https://github.com/Railgun-Community/wallet/assets/95926324/0405a69f-6b5b-4dd7-a5f1-a793d03137a2)

![image](https://github.com/Railgun-Community/wallet/assets/95926324/f33f6cb3-dc14-4bd5-beae-34cdfa8c8f28)

**Comment by Zorlin** [comment]
Hi @kamalbuilds - I believe I know a fix for this, will try and get it sorted in the next day or so.

**Comment by zy0n** [comment]
> Hi @kamalbuilds - I believe I know a fix for this, will try and get it sorted in the next day or so.

Using the correct pacakges is the fix. You've got engine version 4.3.5 there which uses the old 'unavailable' package.
Latest engine version is 9.0.1. That is the 'fix'

**Comment by zy0n** [comment]
> > > @zy0n @Zorlin @mesquka can you please check into this and tell me a way to resolve this issue , tried a bunch of stuff but still stuck at this from many days ?
> > 
> > 
> > Am not sure as to which version bun is trying to install; but if you check [@railgun-community/circomlibjs pkg on npmjs](https://www.npmjs.com/package/@railgun-community/circomlibjs) you'll see that its 0.0.8 not 1.1.6 that bun has there?
> > this issue is fixed in that package. try putting 0.0.8 as the resolution version in the package.json as well;
> 
> @zy0n I tried to run a bunch of repos to find which is the ideal setup but the error incurs in all of them .
> 
> Providing some of them below for reference and it doesnt seem a bun issue as I tried with npm and yarn too.
> 
> 1. https://github.com/venture23-zkp/railgun-integrations-ui/blob/develop/package.json
> 2. https://github.com/zkpay-team/dapp

you' will need to update the packages used in those repos to the latest ones;
